.only-default: &only-default
  only:
    - merge_requests
    - master

.print-system-info: &print-system-info
  - lsb_release -a
  - pwd
  - clang++ --version
  - g++ --version
  - git --version

before_script:
  - *print-system-info
  - touch Jamroot
  - source SetEnv_rub.sh

b2, g++ 9.2.0:
  <<: *only-default
  script:
    - bjam release -j$(nproc)

b2, clang 8.0.1:
  <<: *only-default
  script:
    - bjam release toolset=clang -j$(nproc)
