.only-default: &only-default
  only:
    - merge_requests
    - master

.print-system-info: &print-system-info
#  - lsb_release -a
  - git --version
  - pwd
  - g++ --version

Empty job:
  <<: *only-default
  before_script:
    - *print-system-info
  script:
    - echo "Script stage undefined!"

B2 (bjam):
  before_script:
    - *print-system-info
    - touch Jamroot
    - source SetEnv_rubCentos8.sh
  script:
    - bjam release -j$(nproc)
