#!/bin/bash

if [ ! -d build ]
then
mkdir build
fi

if [ ! -d bin ]
then
mkdir bin
fi

if [ ! -d lib ]
then
mkdir lib
fi

cd build

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.. -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER=/usr/local/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/bin/g++
make
make install
