[metadata]
name = PAWIAN
author = Bertram Kopf
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.ep1.rub.de/EP1/Pawian
license = GPLv3 or later
keywords =
    HEP
    PWA
    partial wave analysis
    hadron spectroscopy
    physics
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Intended Audience :: Science/Research
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Natural Language :: English
    Programming Language :: C++
    Operating System :: Unix
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Physics

[options.extras_require]
doc =
    doc8==0.8.1
    myst-parser==0.12.8
    Sphinx==3.2.1
    sphinx-copybutton==0.3.0
    sphinx-rtd-theme==0.5.0
dev =
    %(doc)s
    black==20.8b1
    jupyter==1.0.0
    jupyterlab==2.2.6
    jupyterlab-code-formatter==1.3.6
    jupyter-nbextensions-configurator==0.4.1
    pre-commit==2.7.1
    rstcheck==3.3.1
    tox==3.20.0

[rstcheck]
ignore_substitutions =
  br
report=warning
