CMAKE_MINIMUM_REQUIRED(VERSION 2.4.3 FATAL_ERROR)
set(PACKAGE_NAME qft++)

MESSAGE("cmake installation for package: " ${PACKAGE_NAME})

set(INCLUDE_DIRECTORIES ${CMAKE_SOURCE_DIR})

include_directories( ${INCLUDE_DIRECTORIES})

AUX_SOURCE_DIRECTORY("relativistic-quantum-mechanics" SRC_RQM)
AUX_SOURCE_DIRECTORY("tensor" SRC_TENSOR)

SET ( PAWIAN_SRCS
  ${SRC_RQM}
  ${SRC_TENSOR}
)

# BUILD_SHARED_LIBS controls the behavior of ADD_LIBRARY if STATIC/SHARED omitted
IF( PAWIAN_STATIC )
        ADD_LIBRARY ( ${PACKAGE_NAME} STATIC ${PAWIAN_SRCS} )
ELSE()
        ADD_LIBRARY ( ${PACKAGE_NAME} SHARED ${PAWIAN_SRCS} )
ENDIF( PAWIAN_STATIC )

INSTALL (TARGETS ${PACKAGE_NAME} DESTINATION ${CMAKE_BINARY_DIR}/lib)


