CMAKE_MINIMUM_REQUIRED(VERSION 2.6.3 FATAL_ERROR)

MESSAGE("cmake installation for package: Examples/geneva/GStartProject")

SET (EXECUTABLENAME GStartProject)

SET (${EXECUTABLENAME}_SRCS
    GArgumentParser 
	GStartProject

)

SET (CONFIGURATIONFILES
    GStartProject.cfg
)

ADD_EXECUTABLE(${EXECUTABLENAME}
	${${EXECUTABLENAME}_SRCS}
)
MESSAGE("GENEVA_ROOT: ${GENEVA_ROOT}")
SET (INCLUDE_DIRECTORIES
     ${CMAKE_SOURCE_DIR}
     ${Boost_INCLUDE_DIRS}
     ${GENEVA_INCLUDE_DIRS}
     ${GENEVA_ROOT}/examples/include )

INCLUDE_DIRECTORIES (AFTER 
        ${CMAKE_SOURCE_DIR}
        ${Boost_INCLUDE_DIRS}
	${GENEVA_INCLUDE_DIRS}
        ${GENEVA_ROOT}/examples/include
)

TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${GENEVA_LIBRARY})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})


