CMAKE_MINIMUM_REQUIRED(VERSION 2.4.3 FATAL_ERROR)

set(PACKAGE_NAME tensor)


set(INCLUDE_DIRECTORIES
${TOP_DIR}/qft++/tensor
${TOP_DIR}/qft++/c++-template-utils
${TOP_DIR}/qft++/matrix
)

include_directories( ${INCLUDE_DIRECTORIES})

SET ( PAWIANSRCS
TensorIndex.cc
)

# BUILD_SHARED_LIBS controls the behavior of ADD_LIBRARY if STATIC/SHARED omitted
IF( PAWIAN_STATIC )
        ADD_LIBRARY ( ${PROJECT_NAME} STATIC ${PAWIANSRCS} )
ELSE()
        ADD_LIBRARY ( ${PROJECT_NAME} SHARED ${PAWIANSRCS} )
ENDIF( PAWIAN_STATIC )


#target_link_libraries(${PACKAGE_NAME})
INSTALL (TARGETS ${PACKAGE_NAME} LIBRARY DESTINATION ${CMAKE_BINARY_DIR}/lib)


