CMAKE_MINIMUM_REQUIRED(VERSION 2.6.3 FATAL_ERROR)

set(PACKAGE_NAME EtacToapi0Fit)

MESSAGE("cmake installation for package: " ${PACKAGE_NAME})


set(INCLUDE_DIRECTORIES
 ${ROOT_INCLUDE_DIR}
 ${Minuit2_INCLUDE_DIRS}
 ${Boost_INCLUDE_DIRS}
 ${CMAKE_SOURCE_DIR}
 ${GENEVA_INCLUDE_DIRS}
)

include_directories( ${INCLUDE_DIRECTORIES})


AUX_SOURCE_DIRECTORY("." SRC)
Set(CCSRC "")

FOREACH (THEFILE ${SRC})
 IF (NOT ${THEFILE} MATCHES "(.*)App(.*)")
  SET (CCSRC ${CCSRC} ${THEFILE})
 ENDIF()
ENDFOREACH(THEFILE)

# BUILD_SHARED_LIBS controls the behavior of ADD_LIBRARY if STATIC/SHARED omitted
IF( PAWIAN_STATIC )
        ADD_LIBRARY ( ${PACKAGE_NAME} STATIC ${CCSRC} )
ELSE()
        ADD_LIBRARY ( ${PACKAGE_NAME} SHARED ${CCSRC} )
ENDIF( PAWIAN_STATIC )


INSTALL (TARGETS ${PACKAGE_NAME} DESTINATION ${CMAKE_BINARY_DIR}/lib)

######## Linking Geneva app GEtacToapi0FitApp ###########################
SET (EXECUTABLENAME GEtacToapi0FitApp)
ADD_EXECUTABLE( ${EXECUTABLENAME}
   GEtacToapi0FitApp.cc
)
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} EtacToapi0Fit )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ErrLogger )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${ROOT_LIBRARIES} )
# TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Minuit2_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${GENEVA_LIBRARY} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} qft++ )

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})
######## End of linking Geneva app GEtacToapi0FitApp ###########################


######## Linking Minuit2 app MEtacToapi0FitApp ###########################
SET (EXECUTABLENAME MEtacToapi0FitApp)
ADD_EXECUTABLE( ${EXECUTABLENAME}
   MEtacToapi0FitApp.cc
)
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} EtacToapi0Fit )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ErrLogger )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${ROOT_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Minuit2_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} qft++ )

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})
######## End of linking Minuit2 app MEtacToapi0FitApp ###########################
