CMAKE_MINIMUM_REQUIRED(VERSION 2.4.3 FATAL_ERROR)

MESSAGE("cmake installation for package: Examples/qft++")

if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
endif(COMMAND cmake_policy)

SET (EXECUTABLENAME compton_scatteringApp)
SET (EXECUTABLENAME1 SeqDecayHeliAmpsApp)

SET (INCLUDE_DIRECTORIES 
     ${ROOT_INCLUDE_DIR}
     ${CMAKE_SOURCE_DIR} )

SET (${EXECUTABLENAME}_SRCS 
	compton_scattering.cc
)

SET (${EXECUTABLENAME1}_SRCS 
	SeqDecHeliAmps.cc
	SeqDecayHeliAmpsMain.cc
)

ADD_EXECUTABLE(${EXECUTABLENAME}
	${${EXECUTABLENAME}_SRCS}
)

ADD_EXECUTABLE(${EXECUTABLENAME1}
	${${EXECUTABLENAME1}_SRCS}
)

INCLUDE_DIRECTORIES (AFTER
#	${PROJECT_SOURCE_DIR}/examples/SampleIndividuals
 ${ROOT_INCLUDE_DIR}
 ${CMAKE_SOURCE_DIR}
)

TARGET_LINK_LIBRARIES (${EXECUTABLENAME}
        qft++
)


#LINK_DIRECTORIES(${ROOT_LIBRARY_DIR})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME1}
        qft++
	${ROOT_LIBRARIES}
)

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})
INSTALL ( TARGETS ${EXECUTABLENAME1} DESTINATION bin/${EXECUTABLENAME1})

