CMAKE_MINIMUM_REQUIRED(VERSION 2.6.3 FATAL_ERROR)

set(PACKAGE_NAME pbarpToOmegaPi)

MESSAGE("cmake installation for package: " ${PACKAGE_NAME})


set(INCLUDE_DIRECTORIES
 ${ROOT_INCLUDE_DIR}
 ${Minuit2_INCLUDE_DIRS}
 ${log4cpp_INCLUDE_DIRS}
 ${Boost_INCLUDE_DIRS}
 ${CMAKE_SOURCE_DIR}
 ${GENEVA_INCLUDE_DIRS}
)

include_directories( ${INCLUDE_DIRECTORIES})


AUX_SOURCE_DIRECTORY("." SRC)
Set(CCSRC "")

FOREACH (THEFILE ${SRC})
 IF (NOT ${THEFILE} MATCHES "(.*)App(.*)")
  SET (CCSRC ${CCSRC} ${THEFILE})
 ENDIF()
ENDFOREACH(THEFILE)

#BUILD_SHARED_LIBS controls the behavior of ADD_LIBRARY if STATIC/SHARED omitted
IF( PAWIAN_STATIC )
        ADD_LIBRARY ( ${PACKAGE_NAME} STATIC ${CCSRC} )
ELSE()
        ADD_LIBRARY ( ${PACKAGE_NAME} SHARED ${CCSRC} )
ENDIF( PAWIAN_STATIC )


INSTALL (TARGETS ${PACKAGE_NAME} DESTINATION ${CMAKE_BINARY_DIR}/lib)

######## Linking Minuit2 app MEtacToapi0FitApp ###########################
SET (EXECUTABLENAME MpbarpToOmegaPiApp)
ADD_EXECUTABLE( ${EXECUTABLENAME}
   MOmegaPiApp.cc
)

TARGET_LINK_LIBRARIES (${EXECUTABLENAME} pbarpToOmegaPi )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Setup )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Particle )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Event )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Utils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} PwaUtils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ErrLogger )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${ROOT_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Minuit2_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} qft++ )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${log4cpp_LIBRARIES} )

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})
######## End of linking Minuit2 app MEtacToapi0FitApp ###########################

######## Linking Geneva app GOmegaPiApp ###########################
SET (EXECUTABLENAME GOmegaPiApp)
ADD_EXECUTABLE( ${EXECUTABLENAME}
   GOmegaPiApp.cc
)

TARGET_LINK_LIBRARIES (${EXECUTABLENAME} pbarpToOmegaPi )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Setup )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Particle )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Event )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Utils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} PwaUtils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ErrLogger )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${ROOT_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${GENEVA_LIBRARY} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} qft++ )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${log4cpp_LIBRARIES} )

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})

######## End of Linking Geneva app GOmegaPiApp ###########################

######## Linking Serialization app TestApp ###########################
SET (EXECUTABLENAME SerTestApp)
ADD_EXECUTABLE( ${EXECUTABLENAME}
   serializationTestApp.C
)

TARGET_LINK_LIBRARIES (${EXECUTABLENAME} pbarpToOmegaPi )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Setup )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Particle )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Event )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} Utils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} PwaUtils )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ErrLogger )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${ROOT_LIBRARIES} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${GENEVA_LIBRARY} )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${Boost_LIBRARIES})
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} qft++ )
TARGET_LINK_LIBRARIES (${EXECUTABLENAME} ${log4cpp_LIBRARIES} )

INSTALL ( TARGETS ${EXECUTABLENAME} DESTINATION bin/${EXECUTABLENAME})

######## End of Linking Serialization app TestApp ###########################
